name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-labels.yaml'
      - '.github/labels/label-definition.yaml'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - '.github/workflows/sync-labels.yaml'
      - '.github/labels/label-definition.yaml'

jobs:

  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels/label-definition.yaml
          skip-delete: false
          dry-run: false
